### PR TITLE
fix invalid /etc/machine-id

### LINKED ISSUE #89: invalid machine-id
The new function shortid which has been introduced for logging purposes (I think), causes the id which is passed to the "prestart" function to be only 12 characters long, this is what is eventually written to "/etc/machine-id" in the container.

Now, if systemd inside the spawned container tries to read this id, it regards it as "invalid", because it's not long enough, resulting in this message in this boot message:

> Initializing machine ID from random generator.

The result is that a new machine-id is created on every boot and the journal is written to that directory (so it's not ending up in the mounted /var/log/journal/machine-id directory on the host).

I think we end up here:
https://github.com/systemd/systemd/blob/master/src/core/machine-id-setup.c
at the line that says:

> * Hmm, so, the id currently stored is not useful, then let's generate one */

If I change this:

> return strndup(id, 12);

to this:

> return strndup(id, 32);

then it is accepted as a valid machine-id and the message "Initializing machine ID from random generator." disappears ...

So I guess this requires a little bit of refactoring to still have a shortid for logging purposes and a valid machine-id at the same time

### PR DESCRIPTION
**Pull request by brahim-raddahi**
This should fix #89

### CODE REVIEW

File: src/systemdhook.c [hunk 1]
```diff
@@ -691,7 +692,7 @@ static int prestart(const char *rootfs,
 			return -1;
 		}
 
-		rc = dprintf(fd, "%.32s\n", id);
+		rc = dprintf(fd, "%.32s\n", container_uuid);
```
Comment (TomSweeneyRedHat) [inline src/systemdhook.c]: I'm not familiar with dprintf but will assume that if you get a string that's less that 32 char that it will be OK?  If container_uuid's length is less that 32, should we just error out near the top of this function?

File: src/systemdhook.c [hunk 2]
```diff
@@ -1089,7 +1090,7 @@ int main(int argc, char *argv[])
 
 		pr_pdebug("%s: UID: %d", id, uid);
 
-		if (prestart(rootfs, id, target_pid, mount_label, config_mounts, config_mounts_len, uid, gid) != 0) {
+		if (prestart(rootfs, container_uuid, id, target_pid, mount_label, config_mounts, config_mounts_len, uid, gid) != 0) {
```
Comment (TomSweeneyRedHat) [inline src/systemdhook.c]: do you want the id variable in here?  I thought container_uuid would replace it, not be added to the list of params.

Comment (rhatdan) [reply src/systemdhook.c]: This looks like container_uuid is the string "container_uuid=UUID"

**Comment by rhatdan** [comment]
LGTM
@mrunalp PTAL

File: src/systemdhook.c (hunk 1 above)
Comment (brahim-raddahi) [reply src/systemdhook.c]: It will end up with a string < 32 chars, which will in turn result in systemd not accepting it as a valid machine-id, thus creating a random machine-id on boot of the container.

File: src/systemdhook.c (hunk 2 above)
Comment (brahim-raddahi) [reply src/systemdhook.c]: The variable id comes from the shortid function,  which seems to only be used for logging purposes at the moment (it's 12 chars long).

**Comment by mrunalp** [comment]
This seems fine for now. We should do a follow-up to clean-up logging by adding helper to prepend the short id.

**Comment by rhatdan** [comment]
Thanks @brahim-raddahi for the patch.

**Comment by brahim-raddahi** [comment]
Glad to help :)
Thanks for the quick response and merge!
